<form action="/courses" method="post">
    <div>
        <select name="course[paid]" id="">
            <option value="">Select</option>
            <option <?= $course['paid'] === '1' ? 'selected' : '' ?> value="1">Paid</option>
            <option <?= $course['paid'] === '0' ? 'selected' : '' ?> value="0">Free</option>
        </select>
        <?php if (isset($errors['paid'])): ?>
            <div><?= $errors['paid'] ?></div>
        <?php endif ?>
    </div>
    <div>
        <label>Course title
            <input type="text" name="course[title]" value="<?= htmlspecialchars($course['title']) ?>">
        </label>
        <?php if (isset($errors['title'])): ?>
            <div><?= $errors['title'] ?></div>
        <?php endif ?>
    </div>

    <input type="submit" value="Save">
</form>